services:
  mongo:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - my_net

  auth-service:
    build: ./server-authentication
    container_name: auth-service
    stop_signal: SIGINT
    ports:
      - '5555:5555'
    environment:
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - KEYCLOAK_USERNAME=${KEYCLOAK_USERNAME}
      - KEYCLOAK_USER_PASSWORD=${KEYCLOAK_USER_PASSWORD}
      - OIDC_OP_AUTHORIZATION_ENDPOINT=${OIDC_OP_AUTHORIZATION_ENDPOINT}
      - OIDC_OP_ENDSESSION_ENDPOINT=${OIDC_OP_ENDSESSION_ENDPOINT}
      - OIDC_OP_JWKS_ENDPOINT=${OIDC_OP_JWKS_ENDPOINT}
      - OIDC_OP_LOGOUT_ENDPOINT=${OIDC_OP_LOGOUT_ENDPOINT}
      - OIDC_OP_LOGOUT_URL_METHOD=${OIDC_OP_LOGOUT_URL_METHOD}
      - OIDC_OP_TOKEN_ENDPOINT=${OIDC_OP_TOKEN_ENDPOINT}
      - OIDC_OP_USER_ENDPOINT=${OIDC_OP_USER_ENDPOINT}
      - OIDC_RP_CLIENT_ID=${OIDC_RP_CLIENT_ID}
      - OIDC_RP_REALM_ID=${OIDC_RP_REALM_ID}
      - OIDC_RP_CLIENT_SECRET=${OIDC_RP_CLIENT_SECRET}
      - OIDC_RP_SIGN_ALGO=${OIDC_RP_SIGN_ALGO}
    networks:
      - my_net

  exp-service:
    build: ./server-experiment
    container_name: exp-service
    stop_signal: SIGINT
    ports:
      - '5050:5050'
    depends_on:
      - auth-service
      - emf-cloud-service
      - zenoh1
      - zenoh2
      - mongo
      - proxy-service
    networks:
      - my_net

  emf-cloud-service:
    build: ./server-emf-cloud
    container_name: emf-cloud-service
    stop_signal: SIGINT
    ports:
      - '8081:8081'
    networks:
      - my_net

  web-app:
    build: ./web-app
    container_name: web-app
    ports:
      - '7001:7001'
    depends_on:
      - auth-service
      - exp-service
    networks:
      - my_net

  nginx:
    image: nginx:latest
    container_name: nginx-servers
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - auth-service
      - exp-service
    restart: always
    networks:
      - my_net

  zenoh1:
    image: eclipse/zenoh:0.11.0
    container_name: zenoh1
    command: -c /root/.zenoh/zenoh-fs.json5 --adminspace-permissions rw
    restart: unless-stopped
    ports:
      - 17447:7447
      - 18000:8000
    volumes:
      - ./zenoh1:/root/.zenoh
    environment:
      - RUST_LOG=debug
      - ZENOH_BACKEND_FS_ROOT=/root/.zenoh/fs
      - RUST_BACKTRACE=full
    networks:
      my_net:
        ipv4_address: 192.168.10.12

  zenoh2:
    image: eclipse/zenoh:0.11.0
    container_name: zenoh2
    command: -c /root/.zenoh/zenoh-fs.json5 --adminspace-permissions rw
    restart: unless-stopped
    ports:
      - 27447:7447  # Adjust port mapping as needed
      - 28000:8000  # Adjust port mapping as needed
    volumes:
      - ./zenoh2:/root/.zenoh  # Adjust volume mapping as needed
    environment:
      - RUST_LOG=debug
      - ZENOH_BACKEND_FS_ROOT=/root/.zenoh/fs  # Use a different directory for storage
    networks:
      my_net:
        ipv4_address: 192.168.10.15  # Use a unique IP address within the network

  proxy-service:
    image: ghcr.io/yagorezende/extremexp-abacproxy:dev
    #  build:
    #    context: /home/yagorezende/PycharmProjects/ExtremeXP-ABACProxy/
    #    target: builder
    container_name: proxy-service
     # flask requires SIGINT to stop gracefully
     # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - ${FLASK_APP_PORT}:${FLASK_APP_PORT}
    environment:
      - FLASK_APP_HOST=${FLASK_APP_HOST}
      - FLASK_APP_PORT=${FLASK_APP_PORT}
      - FLASK_APP_NAME=${FLASK_APP_NAME}
      - FLASK_APP_DEBUG=${FLASK_APP_DEBUG}
      - FLASK_APP_ENV=${FLASK_APP_ENV}
      - FLASK_APP_SECRET_KEY=${FLASK_APP_SECRET_KEY}
      - FLASK_APP_DATABASE_URI=${FLASK_APP_DATABASE_URI}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - KEYCLOAK_USERNAME=${KEYCLOAK_USERNAME}
      - KEYCLOAK_USER_PASSWORD=${KEYCLOAK_USER_PASSWORD}
      - OIDC_OP_AUTHORIZATION_ENDPOINT=${OIDC_OP_AUTHORIZATION_ENDPOINT}
      - OIDC_OP_ENDSESSION_ENDPOINT=${OIDC_OP_ENDSESSION_ENDPOINT}
      - OIDC_OP_JWKS_ENDPOINT=${OIDC_OP_JWKS_ENDPOINT}
      - OIDC_OP_LOGOUT_ENDPOINT=${OIDC_OP_LOGOUT_ENDPOINT}
      - OIDC_OP_LOGOUT_URL_METHOD=${OIDC_OP_LOGOUT_URL_METHOD}
      - OIDC_OP_TOKEN_ENDPOINT=${OIDC_OP_TOKEN_ENDPOINT}
      - OIDC_OP_USER_ENDPOINT=${OIDC_OP_USER_ENDPOINT}
      - OIDC_RP_CLIENT_ID=${OIDC_RP_CLIENT_ID}
      - OIDC_RP_REALM_ID=${OIDC_RP_REALM_ID}
      - OIDC_RP_CLIENT_SECRET=${OIDC_RP_CLIENT_SECRET}
      - OIDC_RP_SIGN_ALGO=${OIDC_RP_SIGN_ALGO}
    networks:
      my_net:
        ipv4_address: 192.168.10.22

networks:
  my_net:
    driver: bridge
    name: extremexp_network
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
